// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siyaptbxshxaykardjoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeWFwdGJ4c2h4YXlrYXJkam9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTk2OTcsImV4cCI6MjA3MDIzNTY5N30.qZYrJhcWFVcQ07BUP9Cz6OXAQm57413dW2QyDtoy8xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});